language: csharp
mono: none
dotnet: 3.1
solution: FunBase.sln
env:
  - APP_VERSION=1.0.$TRAVIS_BUILD_NUMBER
script:
  - dotnet build src/
  - dotnet test src/

deploy:
  provider: script
  script:
  - dotnet pack src/ --configuration Release -p:Version=$APP_VERSION && dotnet nuget push "src/FunBase/bin/Release/FunBase.$APP_VERSION.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_KEY
  on:
    branch: master
